In [1]:
import sys
import os

# Use current working directory and go one level up
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

# Now you can import your config
from config import api_key

In [2]:
import json

function_definition = [
    {'type': 'function',
     'function': {'name': 'extract_structured_data',
     'description': 'extract dates, descriptions and amounts from text and return in in a',
     'parameters': {'type': 'object',
     'properties': {'home type': {'type': 'string', 'description': 'Home type'},
     'location': {'type': 'string', 'description': 'Location'},
     'price': {'type': 'integer', 'description': 'Price'},
     'bedrooms': {'type': 'integer', 'description': 'Number of bedrooms'}}}}}
]
print(json.dumps(function_definition,indent=4))

[
    {
        "type": "function",
        "function": {
            "name": "extract_structured_data",
            "description": "extract dates, descriptions and amounts from text and return in in a",
            "parameters": {
                "type": "object",
                "properties": {
                    "home type": {
                        "type": "string",
                        "description": "Home type"
                    },
                    "location": {
                        "type": "string",
                        "description": "Location"
                    },
                    "price": {
                        "type": "integer",
                        "description": "Price"
                    },
                    "bedrooms": {
                        "type": "integer",
                        "description": "Number of bedrooms"
                    }
                }
            }
        }
    }
]

In [3]:
import pdfplumber

# PDF lezen
with pdfplumber.open("AFSCHRIFT.pdf") as pdf:
    text = "\n".join(page.extract_text() for page in pdf.pages)

Cannot set non-stroke color because 2 components are specified but only 1 (grayscale), 3 (rgb) and 4 (cmyk) are supported
Cannot set non-stroke color because 2 components are specified but only 1 (grayscale), 3 (rgb) and 4 (cmyk) are supported
Cannot set non-stroke color because 2 components are specified but only 1 (grayscale), 3 (rgb) and 4 (cmyk) are supported
Cannot set non-stroke color because 2 components are specified but only 1 (grayscale), 3 (rgb) and 4 (cmyk) are supported
Cannot set non-stroke color because 2 components are specified but only 1 (grayscale), 3 (rgb) and 4 (cmyk) are supported

In [4]:
text

'Afschrift Platinumcard\nOp ING.nl vind je de antwoorden op veel van je vragen.\nWil je persoonlijk contact? Kijk dan op ing.nl/contact\nPeriode\n05-07-2025 t/m 04-08-2025\nHr S van Weeren\nJohan Willem Frisolaan 27 Rekeningnummer\nNL93 INGB 0005 7762 48\n2252 HC VOORSCHOTEN\nOvereenkomstnummer\n2100 1259 7824\nKredietlimiet (EUR) Bestedingsruimte (EUR)\n7.000,00 7.000,00\nOp 06-08-2025 schrijven wij 900,91 euro af van uw betaalrekening met nummer NL93 INGB 0005 7762 48.\nGeboekt op Naam / Omschrijving / Mededeling Type Bedrag (EUR)\n04-08-2025 AFLOSSING Incasso +900,91\nKaartnummer: 5248 **** **** 5478\n03-08-2025 Google Play Apps Dublin Betaling -11,99\nTransactiedatum: 02-08-2025\nKaartnummer: 5248 **** **** 5478\n03-08-2025 MERPAGO*MATAMBRE CIUDAD DE MEX Betaling -28,33\nTransactiedatum: 02-08-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 593,25 MXN\nKoers: 0,04682\nKoersopslag (EUR): 0,56\n03-08-2025 MERPAGO*GISELAANCONA CIUDAD DE MEX Betaling -120,35\nTransactiedatum: 02-08-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 2520,00 MXN\nKoers: 0,04682\nKoersopslag (EUR): 2,36\n02-08-2025 HOTEL HACIENDA CHICHEN TINUM YUC Betaling -310,87\nTransactiedatum: 31-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 6528,79 MXN\nKoers: 0,04668\nKoersopslag (EUR): 6,09\n02-08-2025 AWS EMEA aws.amazon.co Betaling -0,83\nTransactiedatum: 01-08-2025\nKaartnummer: 5248 **** **** 5478\nPagina 1 van 5\nDit product valt onder het depositogarantiestelsel. Meer weten? Ga naar ing.nl/dgs\nING Bank N.V., statutair gevestigd te Amsterdam, Handelsregister nr. 33031431\n20SPYAP-A\nThis ING message is only archived, not sent.\nAfschrift Platinumcard\nOvereenkomstnummer Periode\n2100 1259 7824 05-07-2025 t/m 04-08-2025\nGeboekt op Naam / Omschrijving / Mededeling Type Bedrag (EUR)\n02-08-2025 REST BARQUITO MAWIMBI LAZARO CARDEN Betaling -82,93\nTransactiedatum: 01-08-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1736,50 MXN\nKoers: 0,04682\nKoersopslag (EUR): 1,62\n01-08-2025 MERPAGO*ELPESCADOR CIUDAD DE MEX Betaling -12,62\nTransactiedatum: 31-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 265,00 MXN\nKoers: 0,04668\nKoersopslag (EUR): 0,25\n01-08-2025 MERPAGO*GLENDYTOURS CIUDAD DE MEX Betaling -255,48\nTransactiedatum: 31-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 5355,00 MXN\nKoers: 0,04677\nKoersopslag (EUR): 5,01\n01-08-2025 Betaling naar creditcard Correctie +800,00\nKaartnummer: 5248 **** **** 5478\n31-07-2025 ABTS CENTRAL TINUM YUC Betaling -6,62\nTransactiedatum: 30-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 140,00 MXN\nKoers: 0,04638\nKoersopslag (EUR): 0,13\n31-07-2025 MERPAGO*MOLCAJETES CIUDAD DE MEX Betaling -25,48\nTransactiedatum: 30-07-2025\nKaartnummer: 5248 **** **** 5478\n30-07-2025 CARACOL PURPURA MERIDA MERIDA YUC Betaling -18,99\nTransactiedatum: 29-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 400,00 MXN\nKoers: 0,04654\nKoersopslag (EUR): 0,37\n30-07-2025 EL LUCERO MERIDA YUC Betaling -45,42\nTransactiedatum: 29-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 956,80 MXN\nKoers: 0,04654\nKoersopslag (EUR): 0,89\nPagina 2 van 5\n20SPYAP-A\nAfschrift Platinumcard\nOvereenkomstnummer Periode\n2100 1259 7824 05-07-2025 t/m 04-08-2025\nGeboekt op Naam / Omschrijving / Mededeling Type Bedrag (EUR)\n29-07-2025 RESTAURANTE MUGY MERIDA YUC Betaling -48,70\nTransactiedatum: 27-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1035,00 MXN\nKoers: 0,04613\nKoersopslag (EUR): 0,96\n29-07-2025 LA TRATTO SANTA LUCIA MERIDA YUC Betaling -73,97\nTransactiedatum: 28-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1558,25 MXN\nKoers: 0,04654\nKoersopslag (EUR): 1,45\n28-07-2025 SORIANA431 MERIDACENTR MERIDA YUC Betaling -13,68\nTransactiedatum: 26-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 290,70 MXN\nKoers: 0,04613\nKoersopslag (EUR): 0,27\n28-07-2025 BURGER KING LOUVRE MERIDA YUC Betaling -19,85\nTransactiedatum: 27-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 422,00 MXN\nKoers: 0,04613\nKoersopslag (EUR): 0,39\n28-07-2025 REST SOBERN STEAKHOUSE MERIDA YUC Betaling -24,14\nTransactiedatum: 27-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 513,19 MXN\nKoers: 0,04613\nKoersopslag (EUR): 0,47\n27-07-2025 HOTEL RANCHO ENCANTADO BACALAR QROO Betaling -312,96\nTransactiedatum: 26-07-2025\nKaartnummer: 5248 **** **** 5478\n26-07-2025 AKI BACALAR BACALAR QROO Betaling -17,39\nTransactiedatum: 24-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 370,46 MXN\nKoers: 0,04602\nKoersopslag (EUR): 0,34\n26-07-2025 REST AJAL BACALAR QROO Betaling -70,39\nTransactiedatum: 25-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1496,00 MXN\nKoers: 0,04613\nKoersopslag (EUR): 1,38\nPagina 3 van 5\n20SPYAP-A\nAfschrift Platinumcard\nOvereenkomstnummer Periode\n2100 1259 7824 05-07-2025 t/m 04-08-2025\nGeboekt op Naam / Omschrijving / Mededeling Type Bedrag (EUR)\n25-07-2025 CHIRINGUITO TULUM SOLIDARIDAD Q Betaling -43,36\nTransactiedatum: 23-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 920,00 MXN\nKoers: 0,0462\nKoersopslag (EUR): 0,85\n25-07-2025 GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY# Betaling -3,49\nTransactiedatum: 23-07-2025\nKaartnummer: 5248 **** **** 5478\n24-07-2025 CHEDRAUI 153 TULUM TULUM QROO Betaling -6,15\nTransactiedatum: 22-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 130,50 MXN\nKoers: 0,04622\nKoersopslag (EUR): 0,12\n23-07-2025 PARQUE JAGUAR CENTRO TULUM QROO Betaling -58,70\nTransactiedatum: 22-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1245,00 MXN\nKoers: 0,04622\nKoersopslag (EUR): 1,15\n22-07-2025 MERPAGO*NEGROHUITLACO CIUDAD DE MEX Betaling -65,77\nTransactiedatum: 21-07-2025\nKaartnummer: 5248 **** **** 5478\nBedrag: 1395,00 MXN\nKoers: 0,04622\nKoersopslag (EUR): 1,29\n21-07-2025 Condor Fl1316521701 Neu-Isenburg Betaling -350,97\nTransactiedatum: 19-07-2025\nKaartnummer: 5248 **** **** 5478\n20-07-2025 Betaling naar creditcard Correctie +400,00\nKaartnummer: 5248 **** **** 5478\n19-07-2025 WWW.STAYCITY.COM DUBLIN 8 Betaling -31,00\nTransactiedatum: 19-07-2025\nKaartnummer: 5248 **** **** 5478\n18-07-2025 GOOGLE*GOOGLE ONE G.CO/HELPPAY# Betaling -2,99\nTransactiedatum: 16-07-2025\nKaartnummer: 5248 **** **** 5478\n18-07-2025 AIRALO SINGAPORE Betaling -22,50\nTransactiedatum: 18-07-2025\nKaartnummer: 5248 **** **** 5478\n10-07-2025 GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY# Betaling -14,99\nTransactiedatum: 09-07-2025\nKaartnummer: 5248 **** **** 5478\nPagina 4 van 5\n20SPYAP-A\nAfschrift Platinumcard\nOvereenkomstnummer Periode\n2100 1259 7824 05-07-2025 t/m 04-08-2025\nGeboekt op Naam / Omschrijving / Mededeling Type Bedrag (EUR)\nPagina 5 van 5\n20SPYAP-A'

In [21]:
from openai import OpenAI

client = OpenAI(api_key=api_key)

# Naar OpenAI sturen voor structuur
response = client.responses.create(
    model="gpt-4.1",  # of gpt-4o
    input=f"Extract the dates (Geboekt op), the description (Naam / Omschrijving / Mededeling), the amounts (Bedrag (EUR)) and return only a response in JSON (I do not want to see the word json in the respone) format from the text provided in triple quotes ```{text}```"
)

print(response.output_text)

[
  {
    "date": "04-08-2025",
    "description": "AFLOSSING Incasso",
    "amount": "+900,91"
  },
  {
    "date": "03-08-2025",
    "description": "Google Play Apps Dublin",
    "amount": "-11,99"
  },
  {
    "date": "03-08-2025",
    "description": "MERPAGO*MATAMBRE CIUDAD DE MEX",
    "amount": "-28,33"
  },
  {
    "date": "03-08-2025",
    "description": "MERPAGO*GISELAANCONA CIUDAD DE MEX",
    "amount": "-120,35"
  },
  {
    "date": "02-08-2025",
    "description": "HOTEL HACIENDA CHICHEN TINUM YUC",
    "amount": "-310,87"
  },
  {
    "date": "02-08-2025",
    "description": "AWS EMEA aws.amazon.co",
    "amount": "-0,83"
  },
  {
    "date": "02-08-2025",
    "description": "REST BARQUITO MAWIMBI LAZARO CARDEN",
    "amount": "-82,93"
  },
  {
    "date": "01-08-2025",
    "description": "MERPAGO*ELPESCADOR CIUDAD DE MEX",
    "amount": "-12,62"
  },
  {
    "date": "01-08-2025",
    "description": "MERPAGO*GLENDYTOURS CIUDAD DE MEX",
    "amount": "-255,48"
  },
  {
    "date": "01-08-2025",
    "description": "Betaling naar creditcard Correctie",
    "amount": "+800,00"
  },
  {
    "date": "31-07-2025",
    "description": "ABTS CENTRAL TINUM YUC",
    "amount": "-6,62"
  },
  {
    "date": "31-07-2025",
    "description": "MERPAGO*MOLCAJETES CIUDAD DE MEX",
    "amount": "-25,48"
  },
  {
    "date": "30-07-2025",
    "description": "CARACOL PURPURA MERIDA MERIDA YUC",
    "amount": "-18,99"
  },
  {
    "date": "30-07-2025",
    "description": "EL LUCERO MERIDA YUC",
    "amount": "-45,42"
  },
  {
    "date": "29-07-2025",
    "description": "RESTAURANTE MUGY MERIDA YUC",
    "amount": "-48,70"
  },
  {
    "date": "29-07-2025",
    "description": "LA TRATTO SANTA LUCIA MERIDA YUC",
    "amount": "-73,97"
  },
  {
    "date": "28-07-2025",
    "description": "SORIANA431 MERIDACENTR MERIDA YUC",
    "amount": "-13,68"
  },
  {
    "date": "28-07-2025",
    "description": "BURGER KING LOUVRE MERIDA YUC",
    "amount": "-19,85"
  },
  {
    "date": "28-07-2025",
    "description": "REST SOBERN STEAKHOUSE MERIDA YUC",
    "amount": "-24,14"
  },
  {
    "date": "27-07-2025",
    "description": "HOTEL RANCHO ENCANTADO BACALAR QROO",
    "amount": "-312,96"
  },
  {
    "date": "26-07-2025",
    "description": "AKI BACALAR BACALAR QROO",
    "amount": "-17,39"
  },
  {
    "date": "26-07-2025",
    "description": "REST AJAL BACALAR QROO",
    "amount": "-70,39"
  },
  {
    "date": "25-07-2025",
    "description": "CHIRINGUITO TULUM SOLIDARIDAD Q",
    "amount": "-43,36"
  },
  {
    "date": "25-07-2025",
    "description": "GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#",
    "amount": "-3,49"
  },
  {
    "date": "24-07-2025",
    "description": "CHEDRAUI 153 TULUM TULUM QROO",
    "amount": "-6,15"
  },
  {
    "date": "23-07-2025",
    "description": "PARQUE JAGUAR CENTRO TULUM QROO",
    "amount": "-58,70"
  },
  {
    "date": "22-07-2025",
    "description": "MERPAGO*NEGROHUITLACO CIUDAD DE MEX",
    "amount": "-65,77"
  },
  {
    "date": "21-07-2025",
    "description": "Condor Fl1316521701 Neu-Isenburg",
    "amount": "-350,97"
  },
  {
    "date": "20-07-2025",
    "description": "Betaling naar creditcard Correctie",
    "amount": "+400,00"
  },
  {
    "date": "19-07-2025",
    "description": "WWW.STAYCITY.COM DUBLIN 8",
    "amount": "-31,00"
  },
  {
    "date": "18-07-2025",
    "description": "GOOGLE*GOOGLE ONE G.CO/HELPPAY#",
    "amount": "-2,99"
  },
  {
    "date": "18-07-2025",
    "description": "AIRALO SINGAPORE",
    "amount": "-22,50"
  },
  {
    "date": "10-07-2025",
    "description": "GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#",
    "amount": "-14,99"
  }
]

In [45]:
import json

#print(response.output_text)
print(type(response.output_text))

json_data = json.loads(response.output_text)
type(json_data)

<class 'str'>

list

In [46]:
import pandas as pd
df = pd.DataFrame(json_data)
df

          date                           description   amount
0   04-08-2025                     AFLOSSING Incasso  +900,91
1   03-08-2025               Google Play Apps Dublin   -11,99
2   03-08-2025        MERPAGO*MATAMBRE CIUDAD DE MEX   -28,33
3   03-08-2025    MERPAGO*GISELAANCONA CIUDAD DE MEX  -120,35
4   02-08-2025      HOTEL HACIENDA CHICHEN TINUM YUC  -310,87
5   02-08-2025                AWS EMEA aws.amazon.co    -0,83
6   02-08-2025   REST BARQUITO MAWIMBI LAZARO CARDEN   -82,93
7   01-08-2025      MERPAGO*ELPESCADOR CIUDAD DE MEX   -12,62
8   01-08-2025     MERPAGO*GLENDYTOURS CIUDAD DE MEX  -255,48
9   01-08-2025    Betaling naar creditcard Correctie  +800,00
10  31-07-2025                ABTS CENTRAL TINUM YUC    -6,62
11  31-07-2025      MERPAGO*MOLCAJETES CIUDAD DE MEX   -25,48
12  30-07-2025     CARACOL PURPURA MERIDA MERIDA YUC   -18,99
13  30-07-2025                  EL LUCERO MERIDA YUC   -45,42
14  29-07-2025           RESTAURANTE MUGY MERIDA YUC   -48,70
15  29-07-2025      LA TRATTO SANTA LUCIA MERIDA YUC   -73,97
16  28-07-2025     SORIANA431 MERIDACENTR MERIDA YUC   -13,68
17  28-07-2025         BURGER KING LOUVRE MERIDA YUC   -19,85
18  28-07-2025     REST SOBERN STEAKHOUSE MERIDA YUC   -24,14
19  27-07-2025   HOTEL RANCHO ENCANTADO BACALAR QROO  -312,96
20  26-07-2025              AKI BACALAR BACALAR QROO   -17,39
21  26-07-2025                REST AJAL BACALAR QROO   -70,39
22  25-07-2025       CHIRINGUITO TULUM SOLIDARIDAD Q   -43,36
23  25-07-2025  GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#    -3,49
24  24-07-2025         CHEDRAUI 153 TULUM TULUM QROO    -6,15
25  23-07-2025       PARQUE JAGUAR CENTRO TULUM QROO   -58,70
26  22-07-2025   MERPAGO*NEGROHUITLACO CIUDAD DE MEX   -65,77
27  21-07-2025      Condor Fl1316521701 Neu-Isenburg  -350,97
28  20-07-2025    Betaling naar creditcard Correctie  +400,00
29  19-07-2025             WWW.STAYCITY.COM DUBLIN 8   -31,00
30  18-07-2025       GOOGLE*GOOGLE ONE G.CO/HELPPAY#    -2,99
31  18-07-2025                      AIRALO SINGAPORE   -22,50
32  10-07-2025  GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#   -14,99

In [47]:
df["amount"] = df["amount"].str.replace(".", "", regex=False).str.replace(",", ".", regex=False).astype(float)

In [48]:
df

          date                           description  amount
0   04-08-2025                     AFLOSSING Incasso  900.91
1   03-08-2025               Google Play Apps Dublin  -11.99
2   03-08-2025        MERPAGO*MATAMBRE CIUDAD DE MEX  -28.33
3   03-08-2025    MERPAGO*GISELAANCONA CIUDAD DE MEX -120.35
4   02-08-2025      HOTEL HACIENDA CHICHEN TINUM YUC -310.87
5   02-08-2025                AWS EMEA aws.amazon.co   -0.83
6   02-08-2025   REST BARQUITO MAWIMBI LAZARO CARDEN  -82.93
7   01-08-2025      MERPAGO*ELPESCADOR CIUDAD DE MEX  -12.62
8   01-08-2025     MERPAGO*GLENDYTOURS CIUDAD DE MEX -255.48
9   01-08-2025    Betaling naar creditcard Correctie  800.00
10  31-07-2025                ABTS CENTRAL TINUM YUC   -6.62
11  31-07-2025      MERPAGO*MOLCAJETES CIUDAD DE MEX  -25.48
12  30-07-2025     CARACOL PURPURA MERIDA MERIDA YUC  -18.99
13  30-07-2025                  EL LUCERO MERIDA YUC  -45.42
14  29-07-2025           RESTAURANTE MUGY MERIDA YUC  -48.70
15  29-07-2025      LA TRATTO SANTA LUCIA MERIDA YUC  -73.97
16  28-07-2025     SORIANA431 MERIDACENTR MERIDA YUC  -13.68
17  28-07-2025         BURGER KING LOUVRE MERIDA YUC  -19.85
18  28-07-2025     REST SOBERN STEAKHOUSE MERIDA YUC  -24.14
19  27-07-2025   HOTEL RANCHO ENCANTADO BACALAR QROO -312.96
20  26-07-2025              AKI BACALAR BACALAR QROO  -17.39
21  26-07-2025                REST AJAL BACALAR QROO  -70.39
22  25-07-2025       CHIRINGUITO TULUM SOLIDARIDAD Q  -43.36
23  25-07-2025  GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#   -3.49
24  24-07-2025         CHEDRAUI 153 TULUM TULUM QROO   -6.15
25  23-07-2025       PARQUE JAGUAR CENTRO TULUM QROO  -58.70
26  22-07-2025   MERPAGO*NEGROHUITLACO CIUDAD DE MEX  -65.77
27  21-07-2025      Condor Fl1316521701 Neu-Isenburg -350.97
28  20-07-2025    Betaling naar creditcard Correctie  400.00
29  19-07-2025             WWW.STAYCITY.COM DUBLIN 8  -31.00
30  18-07-2025       GOOGLE*GOOGLE ONE G.CO/HELPPAY#   -2.99
31  18-07-2025                      AIRALO SINGAPORE  -22.50
32  10-07-2025  GOOGLE*GOOGLE PLAY APP G.CO/HELPPAY#  -14.99

In [50]:
df.amount.sum()

np.float64(-4.796163466380676e-14)